export const Events = {
    REQUEST_USER_SOCKET_ID: 'REQUEST_USER_SOCKET_ID',
    SEND_USER_SOCKET_ID: 'SEND_USER_SOCKET_ID',
    SIGNAL: 'SIGNAL',
    CALL_USER: 'CALL_USER',
    ACCEPT_CALL: 'ACCEPT_CALL',
    CALL_ACCEPTED: 'CALL_ACCEPTED',
};